### ISSUE TITLE
Chi_Tang's Blog

### ISSUE THREAD

**Issue by chitang233** [archlinux-cyou/archlinux.cyou#2]
### The website name

Chi_Tang's Blog

### The website address or IP

https://chitang.tech

### What do you want your subdomain prefix to be?

chitang.archlinux.cyou

### Are you a Arch Linux user?

![My desktop screenshot](https://user-images.githubusercontent.com/59324836/174425000-3fa5fd84-eb87-4d84-99bb-069befcb37ca.png)

### Warning

- [X] I know that

**Comment by RealLanta** [comment]
Pass
